apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  default.conf: |
    server {
      listen 8080;

      location /api/v1/movies {
        proxy_pass http://movie-service-fastapi-service:80/api/v1/movies;
      }

      location /api/v1/casts {
        proxy_pass http://cast-service-fastapi-service:80/api/v1/casts;
      }
    }